# Generated by Django 3.2.6 on 2021-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(default='input your about info'),
        ),
        migrations.AddField(
            model_name='author',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
